name: counter
description: A simple ios counter app
version: 1.0.0+1

# Minimum SDK constraints for Dart and Flutter
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.16.0
  google_sign_in: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# Assets, fonts, etc., can be added here.
flutter:
  uses-material-design: true
